services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: voicetable
      POSTGRES_USER: vtuser
      POSTGRES_PASSWORD: vtpass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vtuser -d voicetable"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine

  web:
    build: ./backend
    user: "${UID:-1000}:${GID:-1000}"
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file: .env
    volumes:
      - ./backend:/app
      - ./data/excel:/data:ro
      - ./data/audio/en:/audio/en:ro
      - ./data/audio/ja:/audio/ja:ro
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8000"

  worker:
    build: ./backend
    user: "${UID:-1000}:${GID:-1000}"
    command: celery -A core worker -l info
    env_file: .env
    volumes:
      - ./backend:/app
      - ./data/excel:/data:ro
      - ./data/audio/en:/audio/en:ro
      - ./data/audio/ja:/audio/ja:ro
    depends_on:
      - web
      - redis
      - db

  beat:
    build: ./backend
    user: "${UID:-1000}:${GID:-1000}"
    command: celery -A core beat -l info
    env_file: .env
    volumes:
      - ./backend:/app
    depends_on:
      - worker

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/static:/app/static:ro
      - ./data/audio/en:/srv/audio/en:ro
      - ./data/audio/ja:/srv/audio/ja:ro
    ports:
      - "80:80"
    depends_on:
      - web
