# Generated by Django 5.0.7 on 2025-08-12 22:03

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('excel_source_path', models.CharField(blank=True, default='', max_length=1024)),
                ('audio_roots', models.JSONField(blank=True, default=dict)),
                ('filename_column', models.CharField(blank=True, default='', max_length=200)),
                ('column_headers', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('audio', models.JSONField(blank=True, default=dict)),
                ('indexed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'row_id'], name='app_datarow_project_7adc9a_idx'), django.contrib.postgres.indexes.GinIndex(fields=['data'], name='app_datarow_data_18e880_gin')],
            },
        ),
        migrations.CreateModel(
            name='AudioIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=16)),
                ('filename_stem', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('mtime', models.DateTimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='app.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'language', 'filename_stem'], name='app_audioin_project_117978_idx')],
                'unique_together': {('project', 'language', 'filename_stem')},
            },
        ),
    ]
